const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const Media = sequelize.define('Media', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true
    },
    userId: {
      type: DataTypes.UUID,
      allowNull: false
    },
    filename: {
      type: DataTypes.STRING,
      allowNull: false
    },
    originalName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    mimeType: {
      type: DataTypes.STRING,
      allowNull: false
    },
    size: {
      type: DataTypes.INTEGER,
      allowNull: false,
      comment: 'File size in bytes'
    },
    url: {
      type: DataTypes.STRING,
      allowNull: false,
      comment: 'MinIO object URL'
    },
    thumbnailUrl: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: 'Thumbnail URL (generated by worker)'
    },
    type: {
      type: DataTypes.ENUM('image', 'document', 'video', 'other'),
      defaultValue: 'other'
    },
    status: {
      type: DataTypes.ENUM('uploading', 'processing', 'ready', 'failed'),
      defaultValue: 'uploading'
    },
    metadata: {
      type: DataTypes.JSONB,
      allowNull: true,
      comment: 'Additional metadata (dimensions, duration, etc.)'
    }
  }, {
    tableName: 'media',
    timestamps: true,
    indexes: [
      {
        fields: ['userId']
      },
      {
        fields: ['type']
      },
      {
        fields: ['status']
      }
    ]
  });

  return Media;
};
